sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t horizon45/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true horizon45/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-860883317711"
  bucket_path: "docker-react-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
