sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t horizon45/docker-react-app -f Dockerfile.dev

script:
  - docker run -e CI=true horizon45/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
